version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "80:8000"
    environment:
      - VITE_GOOGLE_CLIENT_ID=${VITE_GOOGLE_CLIENT_ID}
      - VITE_GOOGLE_CLIENT_SECRET=${VITE_GOOGLE_CLIENT_SECRET}
      - VITE_GOOGLE_DRIVE_URL=${VITE_GOOGLE_DRIVE_URL}
      - VITE_GOOGLE_API_KEY=${VITE_GOOGLE_API_KEY}
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro